version: '3.4'

services:
  #MovieWorld:
  #  container_name: "MovieWorld"
  #  image: "mcr.microsoft.com/mssql/server:2022-latest"
  #  environment: 
  #      SA_PASSWORD: "Hashem136636154"
  #      ACCEPT_EULA: "Y"
  #      MSSQL_PID: Developer
  #      MSSQL_TCP_PORT: 1433
  #  restart: always
  #  ports:
  #      - "1433:1433"

  webapi:
    container_name: "MovieWorld.api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"